#!/usr/bin/env python3
"""Append next-50 rubric labels, merge JSON, rename manifest, move files."""
from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WOUNDS = ROOT / "data" / "geo_data"
SRC = WOUNDS / "snake_images"
CAT = WOUNDS / "categories"
OLD_JSON = WOUNDS / "batch1_first5_labels.json"
NEW_JSON = WOUNDS / "snake_wounds_labels.json"

ALL_CLASSES = [
    "cytotoxic",
    "hemotoxic",
    "neurotoxic",
    "myotoxic",
    "non_venomous",
    "not_snakebite",
    "unknown",
]

# (filename, label, confidence, confidence_before, final_summary,
#  visual_features_observed, visual_features_absent,
#  classes_ruled_out as list[tuple[str,str]], flags, context_factors_detected,
#  tie_break_applied, pre_check_triggered, confidence_adjustments_applied,
#  step1, step2, step3, step4, step5, step6, step7)
# Filename order sorted ascending — next 50 after first batch moves.
BATCH50: list[tuple] = [
    (
        "aug_0_1029.jpg",
        "unknown",
        0.56,
        0.56,
        "Mild localized erythema and slight raised wheal at one puncture without clear hemorrhagic discoloration — hemotoxic dual criteria not met.",
        [
            "Two puncture-like marks on thumb",
            "Localized redness at lower site",
            "Possible very mild focal edema",
        ],
        ["No frank bruising", "No necrosis", "No bullae", "No arcuate tooth rows"],
        [
            ("hemotoxic", "Swelling/reaction too subtle to pair reliably with hemorrhagic sign"),
            ("neurotoxic", "Focal inflammation present — not fully normal skin"),
            ("cytotoxic", "No necrosis or blistering"),
            ("non_venomous", "Fang-like pair not arc rows"),
            ("not_snakebite", "Puncture bite present"),
            ("myotoxic", "No segmental limb enlargement"),
        ],
        [],
        ["CTX8"],
        "T5",
        None,
        [],
        "PC1–PC7 cleared.",
        "Two puncture marks on thumb.",
        "CTX8 no scale.",
        "Hemotoxic requires definite hemorrhagic discoloration with swelling; erythema alone insufficient.",
        "Below 0.75 for hemotoxic; assigned unknown.",
        "T5 minimums not met.",
        "Avoided hemotoxic from erythema alone.",
    ),
    (
        "aug_0_1039.jpg",
        "unknown",
        0.57,
        0.57,
        "Fang pair with trace puncture-site change; minimal erythema at one site prevents full neurotoxic 'completely normal' skin requirement.",
        ["Two puncture marks", "Very minimal localized redness at one puncture", "No swelling"],
        ["No bruising", "No necrosis", "No bleeding spread"],
        [
            ("neurotoxic", "Surrounding skin not completely devoid of reaction"),
            ("hemotoxic", "No swelling with hemorrhagic discoloration"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite pattern"),
            ("myotoxic", "No diffuse swelling"),
        ],
        [],
        ["CTX8"],
        "T4",
        None,
        [],
        "Cleared.",
        "Two punctures.",
        "CTX8.",
        "Borderline between neurotoxic-pattern and unknown due to minimal erythema.",
        "Neuro minimum context not satisfied under strict Step 4 wording.",
        "T4 equipoise.",
        "Did not force neurotoxic.",
    ),
    (
        "aug_0_1059.jpg",
        "unknown",
        0.54,
        0.54,
        "Edge distortion and elongated erythematous puncture prevent strict assignment of hemotoxic or neurotoxic.",
        ["Two red marks", "One more linear/scratch-like"],
        ["No swelling", "No bruising", "No necrosis"],
        [
            ("hemotoxic", "No paired swelling and hemorrhagic spread"),
            ("neurotoxic", "Lesion morphology not two clean punctures without any bleeding sign"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Puncture pattern likely bite"),
            ("non_venomous", "Not clear arc rows"),
            ("myotoxic", "N/A"),
        ],
        ["image_edge_artifacts"],
        ["CTX7"],
        "T4",
        None,
        ["CTX7 edge degradation"],
        "Mild edge artifact; central assessable.",
        "Dual puncture-type marks.",
        "CTX7.",
        "Ambiguous morphology.",
        "Confidence below class floors.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1060.jpg",
        "unknown",
        0.55,
        0.55,
        "Prominent fang punctures with fresh blood plus U-shaped smaller tooth row — mixed dentition pattern not mappable to a single class.",
        [
            "Two deeper punctures with fresh blood",
            "Curved row of smaller marks",
            "Minimal swelling",
        ],
        ["No necrosis", "No bullae", "No ecchymosis"],
        [
            ("neurotoxic", "Bleeding present"),
            ("hemotoxic", "Significant swelling absent"),
            ("non_venomous", "Distinct twin fangs plus blood"),
            ("cytotoxic", "No necrosis"),
            ("myotoxic", "N/A"),
            ("not_snakebite", "Bite"),
        ],
        ["multiple_wounds"],
        ["CTX8"],
        "T4",
        None,
        [],
        "PC8 multiple wound elements.",
        "Mixed fang and tooth-row pattern.",
        "CTX8.",
        "Tie between patterns.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_107.jpg",
        "neurotoxic",
        0.63,
        0.68,
        "Twin punctures, flat limb, no swelling or bruising; low resolution reduces confidence within neuro band.",
        ["Two punctures", "Mild perilesional pink only", "Fabric pressure marks nearby"],
        ["Swelling", "Ecchymosis", "Necrosis", "Active bleeding"],
        [
            ("hemotoxic", "No swelling with hemorrhage"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang spacing not arc row"),
            ("not_snakebite", "Punctures present"),
            ("myotoxic", "N/A"),
            ("unknown", "Not chosen — neuro pattern adequate"),
        ],
        [],
        ["CTX7", "CTX8"],
        "T9",
        None,
        ["CTX7 soft focus: −0.05"],
        "PC cleared.",
        "Fang pair.",
        "CTX7/8.",
        "Priority 4 neurotoxic wound appearance.",
        "0.63 within 0.60–0.70.",
        "T9.",
        "Cap respected.",
    ),
    (
        "aug_0_1111.jpg",
        "unknown",
        0.56,
        0.62,
        "Fang marks with faint surrounding purplish discoloration — violates neurotoxic 'no discoloration'; insufficient for hemotoxic without swelling.",
        ["Two punctures", "Faint purplish-pink halo"],
        ["No swelling", "No necrosis"],
        [
            ("neurotoxic", "Discoloration present"),
            ("hemotoxic", "Swelling absent"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        ["CTX8"],
        "T4",
        None,
        ["Mild discoloration penalty to neuro pathway"],
        "Cleared.",
        "Two punctures with halo.",
        "CTX8.",
        "Equipoise.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1113.jpg",
        "hemotoxic",
        0.84,
        0.84,
        "Localized digit swelling with purplish bruising around paired punctures — hemorrhagic discoloration plus edema.",
        ["Index finger edema", "Ecchymosis at punctures", "Fang pair"],
        ["Necrosis", "Bullae", "Whole-hand-only blistering"],
        [
            ("cytotoxic", "No surface necrosis overriding"),
            ("neurotoxic", "Swelling and bruising"),
            ("non_venomous", "Fang with reaction"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "Digit-local not whole limb segment"),
            ("unknown", "Confidence adequate"),
        ],
        [],
        ["CTX8"],
        "T2",
        None,
        [],
        "Cleared.",
        "Fang pair with reaction.",
        "CTX8.",
        "Priority 3 hemotoxic.",
        "0.84 in band.",
        "T2.",
        "None.",
    ),
    (
        "aug_0_1128.jpg",
        "hemotoxic",
        0.82,
        0.82,
        "Localized swelling and erythema with dark punctures consistent with hemorrhage plus edema.",
        ["Two punctures", "Raised edematous plaque", "Perilesional erythema"],
        ["Necrosis", "Bullae", "Distant ecchymosis"],
        [
            ("cytotoxic", "No necrosis"),
            ("neurotoxic", "Swelling present"),
            ("non_venomous", "Fang pair with reaction"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "Localized only"),
            ("unknown", "Met hemotoxic criteria"),
        ],
        ["PC9"],
        ["CTX8"],
        "T2",
        None,
        [],
        "PC9 partially obscured by glare at periphery; center clear.",
        "Fang pair.",
        "CTX8.",
        "Hemotoxic.",
        "In band.",
        "T2.",
        "None.",
    ),
    (
        "aug_0_113.jpg",
        "neurotoxic",
        0.66,
        0.66,
        "Clean twin punctures without swelling, bruising, or bleeding; ink line is monitoring mark not injury.",
        ["Two punctures", "Purple ink demarcation line", "Flat skin"],
        ["Swelling", "Ecchymosis", "Bleeding", "Necrosis"],
        [
            ("hemotoxic", "No edema or bruising"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair not arc"),
            ("not_snakebite", "Snakebite punctures"),
            ("myotoxic", "N/A"),
            ("unknown", "Confidence within neuro band"),
        ],
        [],
        [],
        "T9",
        None,
        [],
        "Cleared.",
        "Fang pair + ink monitoring line.",
        "None.",
        "Neurotoxic wound-only pattern.",
        "≤0.70.",
        "T9.",
        "None.",
    ),
    (
        "aug_0_1133.jpg",
        "hemotoxic",
        0.79,
        0.79,
        "Dark skin: localized swelling with purplish puncture focus — hemorrhagic discoloration plus edema at web space.",
        ["Puncture with hematoma appearance", "Localized edema", "Second possible puncture"],
        ["Necrosis", "Bullae", "Whole-limb shot"],
        [
            ("neurotoxic", "Swelling present"),
            ("cytotoxic", "No frank necrosis overriding hemotoxic"),
            ("non_venomous", "Reaction present"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "Localized"),
            ("unknown", "Meets hemotoxic threshold"),
        ],
        ["human_review_recommended"],
        ["CTX3", "CTX7"],
        "T2",
        None,
        [],
        "Edge artifact right; bite assessable.",
        "Puncture with swelling.",
        "CTX3 dark skin; CTX7 flash glare.",
        "Hemotoxic.",
        "0.79.",
        "T2.",
        "T8 noted — still meets threshold.",
    ),
    (
        "aug_0_115.jpg",
        "hemotoxic",
        0.77,
        0.77,
        "Dried blood at punctures with localized wheal/edema and dark puncture points — hemorrhage sign plus swelling.",
        ["Two punctures", "Perilesional pale elevation", "Dark puncture cores"],
        ["Necrosis", "Extensive ecchymosis", "Bullae"],
        [
            ("neurotoxic", "Edema/wheal present"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang marks"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "Not whole segment"),
            ("unknown", "Criteria met"),
        ],
        [],
        ["CTX7"],
        "T2",
        None,
        [],
        "Cleared.",
        "Fang pair on leg.",
        "CTX7 harsh flash.",
        "Hemotoxic.",
        "In band.",
        "T2.",
        "None.",
    ),
    (
        "aug_0_1165.jpg",
        "unknown",
        0.55,
        0.55,
        "Arcuate tooth marks with dried blood at punctures — fails non_venomous 'no bleeding' and not hemotoxic without swelling.",
        ["U-shaped small punctures", "Trace dried blood each site"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("non_venomous", "Bleeding at punctures"),
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Multi-tooth arc"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Snakebite arc"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T5",
        None,
        [],
        "Cleared.",
        "Arc rows.",
        "None.",
        "Ambiguous.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1168.jpg",
        "hemotoxic",
        0.86,
        0.86,
        "Fang pair with visible ecchymosis and mild localized swelling — both requirements met.",
        ["Bruising between punctures", "Mild edema", "Erythema"],
        ["Necrosis", "Bullae"],
        [
            ("cytotoxic", "No necrosis priority"),
            ("neurotoxic", "Swelling/discoloration"),
            ("non_venomous", "Fang with reaction"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "Localized"),
            ("unknown", "High confidence hemotoxic"),
        ],
        [],
        ["CTX8"],
        "T2",
        None,
        [],
        "Edge smear right; wound clear.",
        "Fang pair.",
        "CTX8.",
        "Hemotoxic.",
        "In band.",
        "T2.",
        "None.",
    ),
    (
        "aug_0_1175.jpg",
        "unknown",
        0.56,
        0.56,
        "Multi-tooth arc with punctate hemorrhage — non_venomous requires zero bleeding.",
        ["U-shaped rows", "Upper linear row", "Pinprick hemorrhages"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("non_venomous", "Bleeding present"),
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Multi puncture"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T5",
        None,
        [],
        "Cleared.",
        "Arc rows.",
        "None.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1190.jpg",
        "unknown",
        0.54,
        0.54,
        "Active bleeding at twin ankle punctures without swelling — cannot assign hemotoxic or neurotoxic.",
        ["Two punctures", "Fresh blood droplets"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Bleeding"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T5",
        None,
        [],
        "Cleared.",
        "Ankle bites.",
        "None.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1200.jpg",
        "unknown",
        0.55,
        0.55,
        "U-shaped abrasions with pinpoint bleeding — non_venomous strict no-bleed not met.",
        ["Semi-circular rows", "Pinpoint blood"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("non_venomous", "Bleeding"),
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Multi teeth"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        ["PC9"],
        ["CTX7"],
        "T5",
        None,
        ["CTX7 blur"],
        "Blur present; bite visible.",
        "Arc bite.",
        "CTX7.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1203.jpg",
        "unknown",
        0.52,
        0.52,
        "Arc cluster plus separate deeper bleeding puncture — mixed pattern.",
        ["Arc of small marks", "Single larger bleeding puncture"],
        ["Swelling", "Bruising"],
        [
            ("non_venomous", "Suspicious deeper puncture"),
            ("neurotoxic", "Multi marks + blood"),
            ("hemotoxic", "No swelling"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        ["multiple_wounds"],
        [],
        "T4",
        None,
        [],
        "PC8.",
        "Mixed.",
        "None.",
        "unknown.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1210.jpg",
        "unknown",
        0.58,
        0.58,
        "Twin fangs with visible erythematous flare — not 'completely normal' skin for neurotoxic.",
        ["Two punctures", "Pink halo ~2–3 cm"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("neurotoxic", "Erythema beyond puncture point"),
            ("hemotoxic", "No clear second sign pairing"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T4",
        None,
        [],
        "Cleared.",
        "Fang pair.",
        "None.",
        "unknown.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1235.jpg",
        "non_venomous",
        0.77,
        0.77,
        "Superficial curved scratch-like tooth rows without swelling, bruising, or substantial bleeding.",
        ["U-shaped superficial red lines", "No deep fangs"],
        ["Swelling", "Ecchymosis", "Necrosis", "Profuse bleeding"],
        [
            ("hemotoxic", "No reaction"),
            ("neurotoxic", "Not two clean fangs"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Snake tooth imprint"),
            ("myotoxic", "N/A"),
            ("unknown", "Meets non_venomous"),
        ],
        [],
        ["CTX8"],
        "T3",
        None,
        [],
        "Warped periphery; center clear.",
        "Arc scratches.",
        "CTX8.",
        "non_venomous.",
        "≥0.75.",
        "T3.",
        "None.",
    ),
    (
        "aug_0_1250.jpg",
        "unknown",
        0.56,
        0.56,
        "Twin punctures with thin red streak — bleeding violates strict neuro; no swelling for hemotoxic.",
        ["Two punctures", "Linear streak from one"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("neurotoxic", "Streak suggests bleeding"),
            ("hemotoxic", "No swelling"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T5",
        None,
        [],
        "Cleared.",
        "Fang pair.",
        "None.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1255.jpg",
        "unknown",
        0.53,
        0.53,
        "Petechiae and puncture cluster without gross swelling — cannot confirm hemotoxic dual criteria.",
        ["Petechiae", "Puncture cluster", "Blur/low resolution"],
        ["Obvious edema", "Necrosis"],
        [
            ("hemotoxic", "Swelling not evident"),
            ("cytotoxic", "No necrosis"),
            ("neurotoxic", "Hemorrhagic stippling"),
            ("non_venomous", "Pattern atypical"),
            ("not_snakebite", "Possible bite injury"),
            ("myotoxic", "N/A"),
        ],
        ["image_edge_artifacts"],
        ["CTX7", "CTX8"],
        "T4",
        None,
        [],
        "Artifact corners.",
        "Hemorrhagic skin signs.",
        "CTX7.",
        "unknown.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1258.jpg",
        "hemotoxic",
        0.78,
        0.78,
        "Web-space swelling and erythema with dark puncture focus — local hemorrhage appearance plus edema.",
        ["Localized edema", "Erythema", "Dark puncture core"],
        ["Bullae", "Obvious necrosis"],
        [
            ("cytotoxic", "No definitive necrosis overriding"),
            ("neurotoxic", "Swelling"),
            ("non_venomous", "Reaction too strong"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "Not whole limb"),
            ("unknown", "Meets hemotoxic"),
        ],
        ["human_review_recommended"],
        ["CTX3"],
        "T2",
        None,
        [],
        "Cleared.",
        "Puncture with reaction.",
        "CTX3.",
        "Hemotoxic.",
        "In band.",
        "T2.",
        "Dark center could be eschar vs clot — review.",
    ),
    (
        "aug_0_127.jpg",
        "unknown",
        0.51,
        0.58,
        "Fang punctures with fresh blood while gloved hand holds gauze — post_first_aid/monitoring context; also bleeding vs neuro conflict.",
        ["Two punctures", "Fresh blood", "Medical glove and gauze"],
        ["Late necrosis"],
        [
            ("neurotoxic", "Blood present"),
            ("hemotoxic", "Swelling not established in view"),
            ("non_venomous", "Fang pair"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        ["post_treatment"],
        ["CTX6"],
        "T5",
        None,
        ["CTX6 features altered — −0.07"],
        "Cleared.",
        "Bite under care.",
        "CTX6.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_128.jpg",
        "unknown",
        0.57,
        0.57,
        "Stock watermark image — clinical authenticity uncertain; puncture pair without swelling.",
        ["Two close punctures", "Watermark visible"],
        ["Swelling", "Bruising"],
        [
            ("not_snakebite", "Cannot verify authentic clinical bite — stock"),
            ("neurotoxic", "Source uncertainty"),
            ("hemotoxic", "No swelling"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang-like close pair"),
            ("myotoxic", "N/A"),
        ],
        ["human_review_recommended"],
        ["CTX8"],
        "T6",
        None,
        [],
        "Cleared subjectively.",
        "Punctures.",
        "Stock asset.",
        "unknown preferred over forced neuro.",
        "unknown.",
        "T6.",
        "Watermark.",
    ),
    (
        "aug_0_1285.jpg",
        "unknown",
        0.55,
        0.55,
        "Arc with fresh puncture bleeding — violates non_venomous zero bleeding.",
        ["U arc", "Fresh blood droplets"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("non_venomous", "Bleeding"),
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Multi teeth"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        ["CTX8"],
        "T5",
        None,
        [],
        "Edge distortion.",
        "Arc bite.",
        "CTX8.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1287.jpg",
        "unknown",
        0.54,
        0.54,
        "Cluster of larger and smaller punctures with bleeding — pattern ambiguous.",
        ["Three prominent bleeding punctures", "Scattered pin marks", "Bounding overlay"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Bleeding and complex pattern"),
            ("non_venomous", "Large punctures"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite-like"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T4",
        None,
        [],
        "Cleared.",
        "Cluster bite.",
        "None.",
        "unknown.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1311.jpg",
        "unknown",
        0.55,
        0.55,
        "Twin punctures with active bleeding trickle; no swelling — rules out hemotoxic and neurotoxic per strict definitions.",
        ["Fang pair", "Blood droplets and trickle"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Bleeding"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        ["CTX8"],
        "T5",
        None,
        [],
        "Low resolution.",
        "Fang pair.",
        "CTX8.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1336.jpg",
        "unknown",
        0.56,
        0.56,
        "Thumb twin lesions: one purplish puncture and one scratch with dried blood — bleeding material present.",
        ["Purplish puncture", "Linear mark with dried blood"],
        ["Gross swelling"],
        [
            ("neurotoxic", "Blood in lesion"),
            ("hemotoxic", "Edema not clearly present"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang-like spacing"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T4",
        None,
        [],
        "Cleared.",
        "Two marks.",
        "None.",
        "unknown.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1343.jpg",
        "unknown",
        0.56,
        0.56,
        "U arc with dried blood per puncture — fails strict non_venomous 'no bleeding'.",
        ["Uniform small punctures arc", "Dried blood dots"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("non_venomous", "Dried blood present"),
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Multi teeth"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        ["CTX8"],
        "T5",
        None,
        [],
        "Smear artifact right.",
        "Arc.",
        "CTX8.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_136.jpg",
        "neurotoxic",
        0.61,
        0.66,
        "Twin hand punctures without edema or discoloration; dim indoor image.",
        ["Two punctures on thumb area", "Flat skin"],
        ["Swelling", "Bruising", "Necrosis", "Bleeding"],
        [
            ("hemotoxic", "No swelling"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
            ("unknown", "Not preferred"),
        ],
        [],
        ["CTX7"],
        "T9",
        None,
        ["CTX7 yellow dim: −0.05"],
        "Low resolution.",
        "Fang pair.",
        "CTX7.",
        "Neurotoxic pattern.",
        "0.61 in band.",
        "T9.",
        "None.",
    ),
    (
        "aug_0_1364.jpg",
        "neurotoxic",
        0.61,
        0.61,
        "Dark skin ankle: twin dried punctures without visible edema or ecchymosis; bruising may be masked.",
        ["Two punctures", "Flat contours"],
        ["Obvious swelling", "Visible bruise"],
        [
            ("hemotoxic", "No visible paired swelling and bruising"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang spacing"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
            ("unknown", "Alternative to neuro"),
        ],
        ["human_review_recommended"],
        ["CTX3", "CTX7", "CTX8"],
        "T9",
        None,
        [],
        "Dim/indoor.",
        "Fang pair.",
        "CTX3/7.",
        "Neuro pattern cautiously; T8 monitoring.",
        "0.61.",
        "T9.",
        "If bruising masked could be hemotoxic — flagged.",
    ),
    (
        "aug_0_137.jpg",
        "unknown",
        0.53,
        0.53,
        "Active bleeding twin punctures without swelling.",
        ["Fresh blood", "Fang pair"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Bleeding"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        ["CTX8"],
        "T5",
        None,
        [],
        "Cleared.",
        "Fang pair.",
        "CTX8.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1374.jpg",
        "hemotoxic",
        0.88,
        0.88,
        "Localized swelling with extensive surrounding ecchymosis around irregular puncture — hemorrhage plus edema.",
        ["Purple bruise", "Raised glossy skin", "Central dark wound"],
        ["Bullae", "Black necrosis"],
        [
            ("cytotoxic", "No clear necrosis over hemotoxic"),
            ("neurotoxic", "Marked reaction"),
            ("non_venomous", "Severe reaction"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "Localized not whole-limb-only"),
            ("unknown", "High confidence"),
        ],
        [],
        ["CTX8"],
        "T2",
        None,
        [],
        "Moderate blur.",
        "Bite with bruise.",
        "CTX8.",
        "Hemotoxic.",
        "In band.",
        "T2.",
        "None.",
    ),
    (
        "aug_0_1393.jpg",
        "neurotoxic",
        0.64,
        0.64,
        "Heel twin punctures with minimal erythema only; no swelling or bruising.",
        ["Two punctures", "Trace pink at sites"],
        ["Swelling", "Ecchymosis", "Necrosis", "Bleeding"],
        [
            ("hemotoxic", "No edema or bruise"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
            ("unknown", "Not required"),
        ],
        [],
        [],
        "T9",
        None,
        [],
        "Cleared.",
        "Heel bite.",
        "None.",
        "Neuro pattern.",
        "≤0.70.",
        "T9.",
        "Trace erythema accepted as puncture-local only.",
    ),
    (
        "aug_0_1396.jpg",
        "unknown",
        0.52,
        0.52,
        "Arc pattern with fresh bleeding — image overlay text ignored; non_venomous requires no bleeding.",
        ["U arc", "Fresh blood", "Overexposure central"],
        ["Swelling", "Bruising"],
        [
            ("non_venomous", "Bleeding"),
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Multi teeth + blood"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        ["PC9"],
        [],
        "T5",
        None,
        [],
        "Overexposure PC9 partially.",
        "Arc.",
        "None.",
        "unknown.",
        "unknown.",
        "T5.",
        "Ignored on-image text per rules.",
    ),
    (
        "aug_0_1407.jpg",
        "unknown",
        0.54,
        0.54,
        "U arc with active oozing blood — non_venomous strict fails.",
        ["Arc punctures", "Active bleeding"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("non_venomous", "Bleeding"),
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Multi teeth"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T5",
        None,
        [],
        "Cleared.",
        "Arc.",
        "None.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1408.jpg",
        "unknown",
        0.52,
        0.52,
        "Twin punctures with edge warping and overexposure — PC1/PC5 risk; minimal signs.",
        ["Two punctures"],
        ["Reliable bruise assessment"],
        [
            ("neurotoxic", "Image quality"),
            ("hemotoxic", "No clear pair"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Uncertain"),
            ("myotoxic", "N/A"),
        ],
        ["poor_image_edges"],
        ["CTX7"],
        "T5",
        None,
        ["CTX7: −0.05"],
        "Borderline PC1.",
        "Punctures.",
        "CTX7.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1413.jpg",
        "unknown",
        0.54,
        0.54,
        "Bleeding punctures without swelling.",
        ["Fresh blood", "Fang pair"],
        ["Swelling", "Bruising"],
        [
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Bleeding"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T5",
        None,
        [],
        "Cleared.",
        "Limb bite.",
        "None.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1416.jpg",
        "neurotoxic",
        0.68,
        0.68,
        "Twin punctures red but described without active bleed spread; flat skin; scale fingers present.",
        ["Fang pair", "Fingers for scale", "No edema"],
        ["Bruising", "Necrosis", "Spreading hemorrhage"],
        [
            ("hemotoxic", "No swelling"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
            ("unknown", "Optional"),
        ],
        [],
        [],
        "T9",
        None,
        [],
        "Cleared.",
        "Fang pair.",
        "Scale via fingers.",
        "Neuro pattern.",
        "≤0.70.",
        "T9.",
        "Educational overlay ignored for class.",
    ),
    (
        "aug_0_1433.jpg",
        "non_venomous",
        0.81,
        0.81,
        "Two U-shaped tooth rows, dried petechiae only, no swelling or bruising.",
        ["Two arc patterns", "Superficial punctures"],
        ["Fang pair", "Swelling", "Ecchymosis", "Necrosis", "Active bleeding"],
        [
            ("neurotoxic", "Multiple teeth not two fangs"),
            ("hemotoxic", "No reaction"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Snakebite"),
            ("myotoxic", "N/A"),
            ("unknown", "Meets non_venomous"),
        ],
        [],
        ["CTX8"],
        "T3",
        None,
        [],
        "Edge blur.",
        "Dual arcs.",
        "CTX8.",
        "non_venomous.",
        "≥0.75.",
        "T3.",
        "Dried spots only — no active bleed.",
    ),
    (
        "aug_0_1437.jpg",
        "unknown",
        0.57,
        0.57,
        "Outdoor twin punctures with dried blood in holes — neuro strict no bleeding fails.",
        ["Fang pair", "Dried intrapunctal blood"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("neurotoxic", "Blood in punctures"),
            ("hemotoxic", "No swelling"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T4",
        None,
        [],
        "Cleared.",
        "Leg bite.",
        "None.",
        "unknown.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1444.jpg",
        "hemotoxic",
        0.83,
        0.83,
        "Heel punctures with surrounding ecchymosis and mild local edema.",
        ["Bruising", "Mild swelling", "Fang slits"],
        ["Necrosis", "Bullae"],
        [
            ("cytotoxic", "No necrosis"),
            ("neurotoxic", "Swelling and bruise"),
            ("non_venomous", "Fang with reaction"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "Localized"),
            ("unknown", "Meets criteria"),
        ],
        [],
        ["CTX3", "CTX7"],
        "T2",
        None,
        [],
        "Cleared.",
        "Heel bite.",
        "CTX3/7.",
        "Hemotoxic.",
        "In band.",
        "T2.",
        "None.",
    ),
    (
        "aug_0_1463.jpg",
        "unknown",
        0.55,
        0.55,
        "Mild edema and erythema without definite ecchymosis — hemotoxic hemorrhagic component unclear.",
        ["Mild swelling", "Redness", "Fang marks", "Fabric grid marks"],
        ["Clear bruising", "Necrosis"],
        [
            ("hemotoxic", "Bruising not definite"),
            ("neurotoxic", "Swelling present"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        ["CTX8"],
        "T4",
        None,
        [],
        "Low resolution.",
        "Fang pair.",
        "CTX8.",
        "unknown.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1498.jpg",
        "unknown",
        0.53,
        0.53,
        "Curved row of small bleeds on finger — not two-fang neuro pattern; non_venomous blocked by active bleeding severity.",
        ["Multiple blood droplets", "Curved arrangement"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("non_venomous", "Active bleeding pattern"),
            ("neurotoxic", "Not two punctures"),
            ("hemotoxic", "No swelling"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Possible bite"),
            ("myotoxic", "N/A"),
        ],
        ["poor_lighting", "human_review_recommended"],
        ["CTX7"],
        "T4",
        None,
        [],
        "Blur/yellow light.",
        "Cluster bite.",
        "CTX7.",
        "unknown.",
        "unknown.",
        "T4.",
        "None.",
    ),
    (
        "aug_0_1501.jpg",
        "unknown",
        0.54,
        0.54,
        "Parallel curved rows with fresh blood — bleeding precludes strict non_venomous.",
        ["Rows of punctures", "Fresh blood"],
        ["Swelling", "Bruising", "Necrosis"],
        [
            ("non_venomous", "Bleeding"),
            ("hemotoxic", "No swelling"),
            ("neurotoxic", "Multi punctures"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        ["watermark_stock"],
        [],
        "T5",
        None,
        [],
        "Watermark present.",
        "Arc rows.",
        "None.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1506.jpg",
        "unknown",
        0.5,
        0.5,
        "Severe overexposure and blur — wound detail unreliable (PC1/PC5).",
        ["Possible U arc red dots"],
        ["Confident swelling assessment", "Depth"],
        [
            ("non_venomous", "Uncertain"),
            ("neurotoxic", "Uncertain"),
            ("hemotoxic", "Uncertain"),
            ("cytotoxic", "No confirmed necrosis"),
            ("not_snakebite", "Uncertain"),
            ("myotoxic", "N/A"),
        ],
        ["poor_exposure"],
        ["CTX7"],
        "T5",
        "PC1",
        ["Overexposure penalty"],
        "PC1 marginal — assign unknown.",
        "Arc suggested.",
        "CTX7 severe.",
        "unknown.",
        "0.50.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1508.jpg",
        "unknown",
        0.54,
        0.62,
        "Dark skin diffuse hand swelling; ecchymosis not visible — cannot meet hemotoxic confidence; single obvious puncture.",
        ["Dorsal hand edema", "One dark puncture", "Silver bracelet glare"],
        ["Visible bruising", "Second fang clearly seen"],
        [
            ("hemotoxic", "CTX3 — bruising not seen; confidence <0.75 after adjustment"),
            ("cytotoxic", "No necrosis"),
            ("neurotoxic", "Swelling present"),
            ("non_venomous", "Reaction present"),
            ("not_snakebite", "Bite likely"),
            ("myotoxic", "Not whole limb in frame"),
        ],
        ["human_review_recommended", "dark_skin_tone"],
        ["CTX3", "CTX7"],
        "T8",
        None,
        ["CTX3 hemotoxic path −0.08"],
        "Cleared.",
        "Swollen hand.",
        "CTX3.",
        "unknown.",
        "unknown.",
        "T8.",
        "None.",
    ),
    (
        "aug_0_1514.jpg",
        "neurotoxic",
        0.65,
        0.65,
        "Forearm twin punctures with ink circle monitoring; no swelling or bruising.",
        ["Fang pair", "Ink demarcation", "Flat skin"],
        ["Edema", "Ecchymosis", "Necrosis", "Bleeding"],
        [
            ("hemotoxic", "No reaction"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
            ("unknown", "Not chosen"),
        ],
        [],
        ["CTX8"],
        "T9",
        None,
        [],
        "Soft focus.",
        "Fang pair.",
        "CTX8.",
        "Neuro.",
        "≤0.70.",
        "T9.",
        "Ink not injury.",
    ),
    (
        "aug_0_1522.jpg",
        "unknown",
        0.55,
        0.55,
        "Twin punctures with blood streak — violates neuro no bleeding.",
        ["Blood streak", "Fang pair"],
        ["Swelling", "Bruising"],
        [
            ("neurotoxic", "Bleeding"),
            ("hemotoxic", "No swelling"),
            ("cytotoxic", "No necrosis"),
            ("non_venomous", "Fang pair"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        [],
        "T5",
        None,
        [],
        "Bright exposure.",
        "Fang pair.",
        "None.",
        "unknown.",
        "unknown.",
        "T5.",
        "None.",
    ),
    (
        "aug_0_1530.jpg",
        "unknown",
        0.54,
        0.54,
        "Cluster of small punctures with fresh blood on thumb web — not two-fang neuro; no swelling for hemotoxic.",
        ["Multiple punctures", "Fresh blood"],
        ["Swelling", "Bruising"],
        [
            ("neurotoxic", "Pattern not two clean fangs"),
            ("hemotoxic", "No swelling"),
            ("non_venomous", "Bleeding + ambiguous arc"),
            ("cytotoxic", "No necrosis"),
            ("not_snakebite", "Bite"),
            ("myotoxic", "N/A"),
        ],
        [],
        ["CTX8"],
        "T4",
        None,
        [],
        "Motion blur.",
        "Cluster.",
        "CTX8.",
        "unknown.",
        "unknown.",
        "T4.",
        "None.",
    ),
]


def ruled_list(pairs: list[tuple[str, str]]) -> list[dict]:
    return [{"class": c, "reason": r} for c, r in pairs]


def make_record(
    fname: str,
    label: str,
    conf: float,
    cb: float,
    final: str,
    obs: list[str],
    absent: list[str],
    ruled: list[tuple[str, str]],
    flags: list[str],
    ctx: list[str],
    tie: str | None,
    pre_t: str | None,
    adj: list[str],
    s1: str,
    s2: str,
    s3: str,
    s4: str,
    s5: str,
    s6: str,
    s7: str,
    cnn_elig: bool,
    cnn_lab: str | None,
    cnn_split: str | None,
) -> dict:
    return {
        "image_path": str((CAT / label / fname).resolve()),
        "label": label,
        "confidence": conf,
        "confidence_before_adjustments": cb,
        "reasoning": {
            "step1_pre_check": s1,
            "step2_snakebite_pattern": s2,
            "step3_context_factors": s3,
            "step4_classification": s4,
            "step5_confidence_check": s5,
            "step6_tie_break": s6,
            "step7_mistake_check": s7,
            "final_summary": final,
        },
        "visual_features_observed": obs,
        "visual_features_absent": absent,
        "classes_considered": ALL_CLASSES.copy(),
        "classes_ruled_out": ruled_list(ruled),
        "flags": flags,
        "pre_check_triggered": pre_t,
        "context_factors_detected": ctx,
        "confidence_adjustments_applied": adj,
        "tie_break_applied": tie,
        "cnn_training_eligible": cnn_elig,
        "cnn_label": cnn_lab,
        "cnn_split": cnn_split,
    }


def cnn_fields(label: str, conf: float, flags: list[str]) -> tuple[bool, str | None, str | None]:
    bad = {"human_review_recommended", "tourniquet_present", "post_treatment"}
    if (
        conf < 0.80
        or label not in ("cytotoxic", "hemotoxic", "neurotoxic", "non_venomous", "not_snakebite")
        or label == "unknown"
        or label == "myotoxic"
        or any(f in bad for f in flags)
    ):
        return False, None, None
    return True, label, "train"  # split adjusted below


def main() -> None:
    existing = json.loads(OLD_JSON.read_text(encoding="utf-8"))
    counters: dict[str, int] = {}
    new_rows: list[dict] = []

    for row in BATCH50:
        (
            fname,
            label,
            conf,
            cb,
            final,
            obs,
            absent,
            ruled,
            flags,
            ctx,
            tie,
            pre_t,
            adj,
            s1,
            s2,
            s3,
            s4,
            s5,
            s6,
            s7,
        ) = row
        elig, clab, csplitr = cnn_fields(label, conf, flags)
        if elig:
            counters[label] = counters.get(label, 0) + 1
            csplitr = "val" if counters[label] % 5 == 0 else "train"
        else:
            clab, csplitr = None, None
        rec = make_record(
            fname,
            label,
            conf,
            cb,
            final,
            obs,
            absent,
            ruled,
            flags,
            ctx,
            tie,
            pre_t,
            adj,
            s1,
            s2,
            s3,
            s4,
            s5,
            s6,
            s7,
            bool(elig),
            clab,
            csplitr,
        )
        new_rows.append(rec)

    merged = existing + new_rows
    NEW_JSON.write_text(json.dumps(merged, indent=2), encoding="utf-8")
    if OLD_JSON.exists() and OLD_JSON != NEW_JSON:
        OLD_JSON.unlink()

    for row in BATCH50:
        fname, label = row[0], row[1]
        src = SRC / fname
        dst_dir = CAT / label
        dst_dir.mkdir(parents=True, exist_ok=True)
        dst = dst_dir / fname
        if not src.exists():
            print("missing", src, file=__import__("sys").stderr)
            continue
        shutil.move(str(src), str(dst))
        # Fix path in record already uses CAT/label

    print("Wrote", NEW_JSON, "total records:", len(merged))
    print("Moved", len(BATCH50), "images into categories/")


if __name__ == "__main__":
    main()
